version: '3.8'

services:
  server:
    container_name: server
    build:
      dockerfile: server.Dockerfile
    ports:
      - '8080:8080'
    expose:
      - '8080'

  client:
    container_name: client
    build:
      dockerfile: client.Dockerfile
    depends_on:
      - server  
