version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: dockerfile/server.Dockerfile
    ports:
      - 8080:8080  

  client:
    container_name: client
    build:
      context: .
      dockerfile: dockerfile/client.Dockerfile
    environment:
      SERVER_ADDRESS: 'server:8080'
    depends_on:
      - server       
